name: qrs
channels:
  - defaults
dependencies:
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py38_0
  - bleach=3.1.0=py_0
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py38_0
  - colorama=0.4.3=py_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py38_0
  - icu=58.2=ha66f8fd_1
  - importlib_metadata=1.5.0=py38_0
  - ipykernel=5.1.4=py38h39e3cac_0
  - ipython=7.12.0=py38h5ca1d4c_0
  - ipython_genutils=0.2.0=py38_0
  - ipywidgets=7.5.1=py_0
  - jedi=0.16.0=py38_0
  - jinja2=2.11.1=py_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py38_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=5.3.4=py38_0
  - jupyter_console=6.1.0=py_0
  - jupyter_core=4.6.1=py38_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.16=h9d3ae62_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=1.1.1=py38he774522_0
  - mistune=0.8.4=py38he774522_1000
  - msys2-conda-epoch=20160418=1
  - nbconvert=5.6.1=py38_0
  - nbformat=5.0.4=py_0
  - notebook=6.0.3=py38_0
  - openssl=1.1.1d=he774522_4
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py38_1
  - parso=0.6.1=py_0
  - pickleshare=0.7.5=py38_1000
  - pip=20.0.2=py38_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.3=py_0
  - pygments=2.5.2=py_0
  - pyqt=5.9.2=py38ha925a31_4
  - pyrsistent=0.15.7=py38he774522_0
  - python=3.8.1=h5fd99cc_1
  - python-dateutil=2.8.1=py_0
  - pywin32=227=py38he774522_1
  - pywinpty=0.5.7=py38_0
  - pyzmq=18.1.1=py38ha925a31_0
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=4.6.0=py_1
  - send2trash=1.5.0=py38_0
  - setuptools=45.2.0=py38_0
  - sip=4.19.13=py38ha925a31_0
  - six=1.14.0=py38_0
  - sqlite=3.31.1=he774522_0
  - terminado=0.8.3=py38_0
  - testpath=0.4.4=py_0
  - tornado=6.0.3=py38he774522_3
  - traitlets=4.3.3=py38_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py38_1
  - wheel=0.34.2=py38_0
  - widgetsnbextension=3.5.1=py38_0
  - wincertstore=0.2=py38_0
  - winpty=0.4.3=4
  - zeromq=4.3.1=h33f27b4_3
  - zipp=2.2.0=py_0
  - zlib=1.2.11=h62dcd97_3
  - pip:
    - beautifulsoup4==4.8.2
    - bs4==0.0.1
    - cmake==3.16.3
    - cycler==0.10.0
    - dlib==19.19.0
    - imutils==0.5.3
    - joblib==0.14.1
    - kiwisolver==1.1.0
    - matplotlib==3.1.3
    - numpy==1.18.1
    - pandas==1.0.1
    - pyedflib==0.1.15
    - pyparsing==2.4.6
    - pytz==2019.3
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - selenium==3.141.0
    - soupsieve==1.9.5
    - urllib3==1.25.8
prefix: C:\Users\user\Anaconda3\envs\qrs

